---
name: create declared labels

"on":
  push:
    branches:
      - master
    paths:
      - ".github/workflows/issue-label-manager.yml"
      - ".github/labels.yml"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labels:
    name: Invoke issue-label-manager action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: crazy-max/ghaction-github-labeler@3de87da19416edc45c90cd89e7a4ea922a3aae5a # tag=v4
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false # false -> delete labels that aren't in `yaml-file`
